spring.application.name=project
spring.datasource.url=jdbc:sqlserver://MPC\\SQLEXPRESS;databaseName=studentdb;encrypt=true;trustServerCertificate=true
spring.datasource.username=ali
spring.datasource.password=738462
spring.datasource.driverClassName=com.microsoft.sqlserver.jdbc.SQLServerDriver
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Admin Setup
app.admin.username=admin
app.admin.password=Dangerous0461
